[package]
name = "ure"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bimap = { version = "0.6.3", features = ["serde"] }
cgmath = "0.18.0"
gl = "0.14.0"
rand = "0.9.1"
rhai = "1.21.0"
ron = "0.10.1"
sdl2 = "0.37.0"
serde = { version = "1.0.219", features = ["derive"] }
softbuffer = "0.4.6"

[features]
default = ["2D"]
2D = []
3D = []
