[package]
name = "ure"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bimap = "0.6.3"
cgmath = "0.18.0"
futures = "0.3.31"
rand = "0.9.1"
raw-window-handle = "0.6.2"
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
wgpu = "25.0.0"
winit = { version = "0.30.10", default-features = false, features = ["rwh_06", "x11"] }

[features]
default = ["2D", "GUI"]
2D = []
3D = []
GUI = []
