[package]
name = "ure"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bimap = "0.6.3"
cgmath = "0.18.0"
rand = "0.9.1"
raw-window-handle = "0.6.2"
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
softbuffer = { version = "0.4.6", default-features = false, features = ["x11", "x11-dlopen"] }
winit = { version = "0.30.10", default-features = false, features = ["x11"] }

[features]
default = ["2D"]
2D = []
3D = []
