[package]
name = "ure"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
gl = "0.14.0"
rand = "0.9.1"
sdl2 = "0.37.0"
softbuffer = "0.4.6"

[features]
default = ["2D"]
2D = []
3D = []
