[package]
name = "ure"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bimap = "0.6.3"
bytemuck = "1.23.0"
futures = "0.3.31"
glam = { version = "0.30.3", features = ["bytemuck"] }
parking_lot = "0.12.3"
rand = "0.9.1"
raw-window-handle = "0.6.2"
rustc-hash = "2.1.1"
serde = "1.0.219"
spin_sleep = "1.3.1"
wgpu = "25.0.0"
winit = { version = "0.30.10" }

[features]
default = ["2D", "GUI"]
2D = []
3D = []
GUI = []
