[package]
name = "ure"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bimap = "0.6.3"
cgmath = "0.18.0"
gl = "0.14.0"
rand = "0.9.1"
ron = "0.10.1"
sdl2 = "0.37.0"
serde = { version = "1.0.219", features = ["derive"] }

[features]
default = ["2D"]
2D = []
3D = []
